import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/ui/header";
import Provider from "@/utils/providers";

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} font-quicksand bg-white bg-none`}>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
